<?php

# This file was automatically generated by the MediaWiki installer.
# If you make manual changes, please keep track in case you need to
# recreate them later.
#
# See includes/DefaultSettings.php for all configurable settings
# and their default values, but don't forget to make changes in _this_
# file, not there.
#
# Further documentation for configuration settings may be found at:
# http://www.mediawiki.org/wiki/Manual:Configuration_settings

# If you customize your file layout, set $IP to the directory that contains
# the other MediaWiki files. It will be used as a base to locate files.
if( defined( 'MW_INSTALL_PATH' ) ) {
	$IP = MW_INSTALL_PATH;
} else {
	$IP = dirname( __FILE__ );
}

$path = array( $IP, "$IP/includes", "$IP/languages" );
set_include_path( implode( PATH_SEPARATOR, $path ) . PATH_SEPARATOR . get_include_path() );

require_once( "$IP/includes/DefaultSettings.php" );

# If PHP's memory limit is very low, some operations may fail.
# ini_set( 'memory_limit', '20M' );

if ( $wgCommandLineMode ) {
	if ( isset( $_SERVER ) && array_key_exists( 'REQUEST_METHOD', $_SERVER ) ) {
		die( "This script must be run from the command line\n" );
	}
}
## Uncomment this to disable output compression
# $wgDisableOutputCompression = true;

$wgSitename         = "NetWiki";

## The URL base path to the directory containing the wiki;
## defaults for all runtime URL paths are based off of this.
## For more information on customizing the URLs please see:
## http://www.mediawiki.org/wiki/Manual:Short_URL
$wgScriptPath       = "/~netexplo/internal";
$wgScriptExtension  = ".php";

## UPO means: this is also a user preference option

$wgEnableEmail      = false;
$wgEnableUserEmail  = false; # UPO

$wgEmergencyContact = "xjqiu@cs.hku.hk";
$wgPasswordSender = "xjqiu@cs.hku.hk";

$wgEnotifUserTalk = true; # UPO
$wgEnotifWatchlist = true; # UPO
$wgEmailAuthentication = true;

## Database settings
$wgDBtype           = "mysql";
$wgDBserver         = "sophia.cs.hku.hk";
$wgDBname           = "netexplo";
$wgDBuser           = "netexplo";
$wgDBpassword       = "xrthsqc323";

# Ajax Enable
$wgUseAjax = true;

# MySQL specific settings
$wgDBprefix         = "";

# MySQL table options to use during installation or update
$wgDBTableOptions   = "ENGINE=InnoDB, DEFAULT CHARSET=binary";

# Experimental charset support for MySQL 4.1/5.0.
$wgDBmysql5 = true;

## Shared memory settings
$wgMainCacheType = CACHE_NONE;
$wgMemCachedServers = array();

## To enable image uploads, make sure the 'images' directory
## is writable, then set this to true:
$wgEnableUploads       = true;
$wgUseImageMagick = true;
$wgImageMagickConvertCommand = "/usr/local/bin/convert";

## If you use ImageMagick (or any other shell command) on a
## Linux server, this will need to be set to the name of an
## available UTF-8 locale
$wgShellLocale = "zh.UTF-8";

## If you want to use image uploads under safe mode,
## create the directories images/archive, images/thumb and
## images/temp, and make them all writable. Then uncomment
## this, if it's not already uncommented:
$wgHashedUploadDirectory = false;

## If you have the appropriate support software installed
## you can enable inline LaTeX equations:
$wgUseTeX           = true;
## $wgMathPath = "http://i.cs.hku.hk/~netexplo/internal/whuang_tex/mimetex.cgi";

$wgLocalInterwiki   = strtolower( $wgSitename );

$wgLanguageCode = "en";

$wgSecretKey = "0af022891d482cecce3b0200db1398194add26eb44a223af19bc8aa490e19f8b";

## Default skin: you can change the default skin. Use the internal symbolic
## names, ie 'standard', 'nostalgia', 'cologneblue', 'monobook':
$wgDefaultSkin = 'monobook';

## For attaching licensing metadata to pages, and displaying an
## appropriate copyright notice / icon. GNU Free Documentation
## License and Creative Commons licenses are supported so far.
# $wgEnableCreativeCommonsRdf = true;
$wgRightsPage = ""; # Set to the title of a wiki page that describes your license/copyright
$wgRightsUrl = "";
$wgRightsText = "";
$wgRightsIcon = "";
# $wgRightsCode = ""; # Not yet used

$wgDiff3 = "";

# Change the timezone to Shanghai
$wgLocaltimezone = "Asia/Shanghai";
putenv("TZ=$wgLocaltimezone");
$wgLocalTZoffset = date("Z") / 60;

# When you make changes to this configuration file, this will make
# sure that cached pages are cleared.
$wgCacheEpoch = max( $wgCacheEpoch, gmdate( 'YmdHis', @filemtime( __FILE__ ) ) );

# Forbidden anonymous user editing the page 
$wgGroupPermissions['*']['edit'] = false;
$wgGroupPermissions['user']['edit'] = true;

# Forbidden anonymous user reading the page 
$wgGroupPermissions['*']['read'] = false;

# Forbidden creation of new user
$wgGroupPermissions['*']['createaccount'] = false;

# Forbidden anonymous user access to Main Page
$wgWhitelistRead = array( "Netexplo_Library","Main Page", "Special:Userlogin", "-", "MediaWiki:Monobook.css",
"Members,_Contact,_and_Schedule",
"Special:RecentChanges",
"Chuan's Schedule",
"Wei's Schedule",
"Chenguang's Schedule",
"Hongxing's Schedule",
"Xuanjia's Schedule",
"Yu's Schedule",
"Jian's Schedule",
"Group_Meeting_Schedule",
"Upcoming Deadlines",
"List of Top Journals/Conferences/Workshops",
"On Paper Survey",
"On Writing Research Papers",
"Introduction to Discrete Event Simulator and P2P Simulators",
"Interesting Talks by Top Researchers",
"Recommended Theory Books/Resources",
"P2P Introduction and Surveys",
"Introduction and Tutorial to Cloud Computing",
"P2P VoD Streaming",
"Locality-aware P2P Designs and Models",
"Modeling of P2P File Sharing and Streaming Systems",
"P2P Incentives",
"Social Network",
"Hybrid P2P+CDN/Cloud",
"Network Economics",
"Cloud Computing",
"Hongxian's Schedule",
"Linquan's Schedule",
"Physical-layer Network Coding",
"Available Hardware Resources",
"Emulation Cluster",
"On Reading/Writing/Presenting Papers",
"Cognitive Radio"
 );

$wgWhitelist['user']['read']  = $wgBlacklist['bot']['read'] = array("News", "Special:RecentChanges", "Fast Neighbor Discovery in P2P VoD Streaming (Xuanjia)", "Modeling the Performance and Locality Tradeoff in BitTorrent-like P2P Systems (Wei)", "Auction Mechanism Design and Analysis for P2P VoD Streaming (Wei and Xuanjia)", "Wireless Scheduling in the SINR Model (Hongxing)", "P2P+Cloud (Yu)", "Modeling of Locality-aware P2P Protocols (Jian)");


$wgLogo="images/49-Compositions.png";
$wgFileExtensions=array('pdf','ppt','ps','rar','jpg','png','tar', 'gz','bz2','7z', 'java', 'm', 'jar', 'c', 'c++', 'cpp', 'doc', 'tex', 'bib');
$wgMaxUploadSize=1024 * 1024 * 5;
$wgUploadSizeWarning= 1024 * 1024 * 5;
$wgShowExceptionDetails = true;
umask(0022);

$wgNamespacesWithSubpages = array_fill(0, 200, true);
# Extension for Sequence Control -- whuang
require_once("extensions/ParserFunctions/ParserFunctions.php");

# The extension for Editor -- whuang
require_once("extensions/MeanEditor/MeanEditor.php");
#require_once("extensions/fckeditor/fckeditor.php");
#require_once("extensions/ckeditor/ckeditor.php");

# The extension for Tex -- whuang
require_once("extensions/mtag.php");

# The extension for Sytax Highlight -- whuang
require_once("extensions/SyntaxHighlight_GeSHi/SyntaxHighlight_GeSHi.php");

# The extension for Update -- whuang
require_once("extensions/DynamicArticleList.php");

# The extension for Access Control -- whuang
# include_once("extensions/blacklist.php");
# require_once("extensions/blacklist.php"); # The extension for Configure -- whuang # require_once("extensions/Configure/Configure.php");
# efConfigureSetup();

# The extension for ForcePreview -- whuang
# $wgGroupPermissions['user']['forcepreviewexempt'] = false; //Does not force preview for registered users
# require_once("extensions/ForcePreview/ForcePreview.php");
?>
